services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/service.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gateway
    depends_on:
      - auth-api
      - example-api

  auth-api:
    build:
      context: ./service.auth
      dockerfile: Dockerfile
    networks:
      - gateway
    ports:
      - "4000:4000"

  example-api:
    build:
      context: ./service.example
      dockerfile: Dockerfile
    networks:
      - gateway
    ports:
      - "4001:4001"

networks:
  gateway:
    driver: bridge